# Generated by Django 4.2.4 on 2023-08-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisements',
        ),
    ]
